version: '3.8'

services:
  web:
    build: .
    # command: python manage.py runserver 0.0.0.0:8000
    command: gunicorn app.wsgi:application --bind 127.0.0.1:8000
    volumes:
      - .:/app
    expose:
      - 8000
    env_file: .env
    depends_on:
      - db
  db:
    image: postgres:13.3-alpine
    restart: always
    volumes:
      - ./data/db:/var/lib/postgresql/data
    env_file: .env-db
    ports:
      - 5433:5433
  
  nginx:
    build: ./nginx
    ports:
      - 8000:80
    depends_on:
      - web

volumes:
  postgres_data: