version: "3.8"
services:
  app:
    build: .
    volumes:
      - .:/delta_nlp
    ports:
      - 8000:8000
    image: app:delta_nlp
    container_name: delta_nlp_container
    command: python manage.py runserver 0.0.0.0:8000